ch1-cartpole-dqn:
    env: CartPole-v1
    run: DQN
    checkpoint_config:
        checkpoint_frequency: 10
    stop:
        episode_reward_mean: 100
        timesteps_total: 100000
    config:
        # Works for both torch and tf.
        framework: torch
        num_gpus: 1
        model:
            fcnet_hiddens: [64]
            fcnet_activation: linear
        n_step: 3