super-mario-dqn:
    env: env.super-mario-env.SuperMarioBrosEnv
    run: DQN
    stop:
        episode_reward_mean: 100
        timesteps_total: 100000
    config:
        # Works for both torch and tf.
        framework: torch
        num_gpus: 1
        model:
            fcnet_hiddens: [64]
            fcnet_activation: linear
        n_step: 3