super-mario-dqn:
    env: env.super_mario_env.SuperMarioBrosEnv
    run: DQN
    checkpoint_config:
        checkpoint_frequency: 1000
    stop:
        timesteps_total: 10000000
    config:
        framework: torch
        num_gpus: 1
        double_q: true
        model:
            #custom_model: models.mario_net.MarioNet
            conv_filters: [
                [32, 8, 4],
                [64, 4, 2],
                [64, 3, 1],
            ]
            conv_activation: "relu"
            post_fcnet_hiddens: [3136, 512]
            post_fcnet_activation: "relu"